site_name: Smallrye Mutiny Zero
repo_url: https://github.com/smallrye/smallrye-mutiny-zero
edit_uri: edit/main/docs/

nav:
  - Overview: 'index.md'
  - 'quick-start.md'
  - Javadoc: './apidocs/index.html'
  - 'flow-adapters.md'
  - 'vertx-based-reactive-streams-publishers.md'

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: white
    accent: red
  font:
  features:
    - navigation.sections

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition

extra:
  manifest: manifest.webmanifest
  version:
    provider: mike
